#!/usr/bin/env bash
# Bootstrap / update script for the AWS free-tier (or any single-VM) deploy.
#
# Idempotent: safe to run on a fresh box AND to re-run after `git pull` to
# rebuild the PWA and restart the stack. See docs/deploy-aws.md.
#
# Usage:
#   DOMAIN=etecstudio.online ./deploy/aws/deploy.sh
#
# Env vars (all optional):
#   DOMAIN   - domain for Caddy/Let's Encrypt (default: etecstudio.online)
#   NODE_IMG - node image used to build frontend/dist (default: node:22-alpine)
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOMAIN="${DOMAIN:-etecstudio.online}"
NODE_IMG="${NODE_IMG:-node:22-alpine}"
MYSQL_SERVICES="mysql redis backend worker nginx"

# Run a docker command on a fresh install, where this shell has no docker
# group yet (no re-login required). After a re-login it runs directly.
docker_cmd() {
    if id -nG "$USER" | grep -qw docker; then
        command docker "$@"
    else
        sg docker -c "docker $*"
    fi
}

echo "==> Repo: ${REPO_DIR}"

# ---------------------------------------------------------------- swap
if [ ! -f /swapfile ]; then
    echo "==> Adding 2 GB swap"
    sudo fallocate -l 2G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
else
    echo "==> Swap already present, skipping"
fi

# ------------------------------------------------------------ docker
if ! command -v docker >/dev/null 2>&1; then
    echo "==> Installing docker"
    sudo apt-get update
    sudo apt-get install -y docker.io docker-compose-v2
fi
sudo usermod -aG docker "$USER" 2>/dev/null || true
DOCKER_GROUP_ID="$(getent group docker | cut -d: -f3)"
echo "==> docker group id: ${DOCKER_GROUP_ID}"

# ------------------------------------------------------------ .env
ENV_FILE="${REPO_DIR}/.env"
if [ ! -f "${ENV_FILE}" ]; then
    echo "==> Creating .env from .env.example (generating secrets)"
    cp "${REPO_DIR}/.env.example" "${ENV_FILE}"
    APP_KEY="base64:$(openssl rand -base64 32)"
    DB_PASS="$(openssl rand -hex 16)"
    DB_ROOT_PASS="$(openssl rand -hex 16)"
    sed -i \
        -e "s|^APP_ENV=.*|APP_ENV=production|" \
        -e "s|^APP_DEBUG=.*|APP_DEBUG=false|" \
        -e "s|^APP_KEY=.*|APP_KEY=${APP_KEY}|" \
        -e "s|^DB_PASSWORD=.*|DB_PASSWORD=${DB_PASS}|" \
        -e "s|^DB_ROOT_PASSWORD=.*|DB_ROOT_PASSWORD=${DB_ROOT_PASS}|" \
        "${ENV_FILE}"
else
    echo "==> .env exists, keeping DB/APP secrets"
    sed -i -e "s|^APP_ENV=.*|APP_ENV=production|" \
           -e "s|^APP_DEBUG=.*|APP_DEBUG=false|" "${ENV_FILE}"
fi

# Set (update or append) host-specific values in .env.
set_env() { # key value
    local key="$1" value="$2"
    if grep -q "^${key}=" "${ENV_FILE}"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "${ENV_FILE}"
    else
        echo "${key}=${value}" >> "${ENV_FILE}"
    fi
}
set_env WORKER_PROCS 1                        # 1 GB VM: one sandbox at a time
set_env DOCKER_GROUP_ID "${DOCKER_GROUP_ID}"  # host docker gid for the socket
set_env EXECUTION_HOST_BASE "${REPO_DIR}/backend"
echo "==> .env ready:"
grep -E '^(APP_ENV|APP_DEBUG|WORKER_PROCS|DOCKER_GROUP_ID|EXECUTION_HOST_BASE)=' "${ENV_FILE}"

# --------------------------------------------- slim php-fpm for 1 GB
FPM="${REPO_DIR}/docker/backend/www.conf"
sed -i \
    -e 's/^pm\.max_children = 12/pm.max_children = 4/' \
    -e 's/^pm\.start_servers = 4/pm.start_servers = 2/' \
    -e 's/^pm\.min_spare_servers = 2/pm.min_spare_servers = 1/' \
    -e 's/^pm\.max_spare_servers = 6/pm.max_spare_servers = 2/' \
    "${FPM}"
echo "==> php-fpm pool slimmed"

# -------------------------------------------------------- sandbox images
echo "==> Building executor images (C / C++ / Python)"
docker_cmd build -t coderunner/c:latest "${REPO_DIR}/executor/c"
docker_cmd build -t coderunner/cpp:latest "${REPO_DIR}/executor/cpp"
docker_cmd build -t coderunner/python:latest "${REPO_DIR}/executor/python"

# -------------------------------------------------------- frontend build
echo "==> Building frontend dist (${NODE_IMG})"
if id -nG "$USER" | grep -qw docker; then
    docker run --rm -v "${REPO_DIR}/frontend:/app" -w /app \
        "${NODE_IMG}" sh -c "npm install --no-audit --no-fund && npm run build"
else
    sg docker -c "docker run --rm -v '${REPO_DIR}/frontend:/app' -w /app ${NODE_IMG} sh -c 'npm install --no-audit --no-fund && npm run build'"
fi

# ---------------------------------------------------------------- caddy
if ! command -v caddy >/dev/null 2>&1; then
    echo "==> Installing caddy"
    sudo apt-get install -y caddy
fi
CADDYFILE="/tmp/caddy.Caddyfile.$$"
cat > "${CADDYFILE}" <<EOF
# Generated by deploy/aws/deploy.sh on $(date -u +%F)
# Let's Encrypt only — ZeroSSL legacy accounts are rejected (code 2977).
{
    admin off
    email ${CADDY_EMAIL:-admin@${DOMAIN}}
    acme_ca https://acme-v02.api.letsencrypt.org/directory
}
${DOMAIN} {
    encode gzip
    reverse_proxy 127.0.0.1:80
}

www.${DOMAIN} {
    redir https://${DOMAIN}{uri} permanent
}
EOF
sudo install -m 0644 "${CADDYFILE}" /etc/caddy/Caddyfile
rm -f "${CADDYFILE}"
sudo systemctl enable --now caddy
sudo systemctl restart caddy
echo "==> Caddy serving ${DOMAIN} (Let's Encrypt auto-provision)"

# ------------------------------------------------------------- compose
echo "==> Starting stack (${MYSQL_SERVICES})"
cd "${REPO_DIR}"
docker_cmd compose -f docker-compose.yml -f docker-compose.prod.yml \
    up -d --build ${MYSQL_SERVICES}

echo "==> Done. Verify:"
echo "    docker compose ps"
echo "    curl -s http://localhost/health    # → ok"
echo "    curl -s http://localhost/          # → index.html"